export { default as Home } from './Home.jsx'
export {default as About } from './About.jsx'
export {default as Resume } from './Resume.jsx'
export {default as Courses } from './Courses.jsx'
export {default as Contact } from './Contact.jsx'
export {default as Education } from './Education.jsx'
export {default as Skills } from './Skills.jsx'